---
version: 2

project_name: mlr

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/mlr
    binary: mlr
    targets:
      - linux_amd64_v2
      - linux_amd64_v4
      - darwin_amd64_v3
      - darwin_arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -X github.com/johnkerl/miller/internal/pkg/version.STRING={{ .RawVersion }}{{ if .Prerelease }}-{{ .Prerelease }}{{ end }}
      - -w
    hooks:
      post:
        - ./scripts/mkman "{{ .Os }}_{{ .Arch }}" "{{ .Path }}"
        - ./scripts/upx "{{ .Path }}"
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}-{{ .RawVersion }}-{{ .Os }}_{{ .Arch }}{{ if .Amd64 }}_{{ .Amd64 }}{{ end }}"
    formats:
      - tar.xz
    wrap_in_directory: true
    files:
      - src: man/mlr.1
        dst: .
        strip_parent: true

snapshot:
  version_template: "{{ .Tag }}-devel"

checksum:
  disable: true

changelog:
  disable: true
