---
project_name: mlr

before:
  hooks:
    - go mod download

builds:
  - main: ./cmd/mlr
    binary: mlr
    targets:
      - linux_amd64
      - darwin_amd64
      - darwin_arm64
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w
      - -X github.com/johnkerl/miller/internal/pkg/version.STRING={{ .RawVersion }}{{ if .Prerelease }}-{{ .Prerelease }}{{ end }}
    hooks:
      post:
        - ./scripts/mkman "{{ .Target }}" "{{ .Path }}"
        - ./scripts/upx "{{ .Path }}"
    env:
      - CGO_ENABLED=0

archives:
  - name_template: "{{ .ProjectName }}-{{ .RawVersion }}-{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format: tar.xz
    wrap_in_directory: "true"
    files:
      - src: man/man1/mlr.1
        dst: .
        strip_parent: true

snapshot:
  name_template: "{{ .Tag }}-devel"

checksum:
  disable: true

changelog:
  skip: true
